[dependencies]

[package]
  cjc-version = "0.53.13"
  compile-option = ""
  description = "A Commander for modern Cangjie CLI interactions. Implementation reference Cobra."
  link-option = ""
  name = "wukong"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = "target"
  version = "0.0.1"
  package-configuration = {}
